apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-source-tbhe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-source-tbhe
    app.kubernetes.io/part-of: test-app-rfxz
  name: build-suite-test-componenx2un
  namespace: build-e2e-oswf-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: build-suite-test-component-image-source-tbhe
    weight: 100
status: {}
